build:
  dependencies:
    before:
      - mkdir -p build/logs
      - mysql -uroot -e 'CREATE DATABASE test'
    override:
      - composer install --prefer-source --no-interaction

  application:
    override:
      -
        command: php artisan migrate --no-interaction
        environment:
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
          DB_DATABASE: 'test'
          APP_ENV: 'local'

  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
        environment:
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
          DB_DATABASE: 'test'
          APP_ENV: 'local'
        coverage:
          file: 'build/logs/clover.xml'
          format: 'php-clover'
