build:
  environment:
    variables:
      DB_USERNAME: root
      DB_PASSWORD: ~
      DB_DATABASE: test
      APP_ENV: local


  dependencies:
    override:
      - composer install --prefer-source --no-interaction

  project_setup:
    before:
      - mkdir -p build/logs
      - mysql -uroot -e 'CREATE DATABASE test'
    override:
      - php artisan migrate --no-interaction

  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
        coverage:
          file: 'build/logs/clover.xml'
          format: 'php-clover'
