language: php

php:
  - 5.5
  - 5.6

env:
  - DB_USERNAME=root DB_DATABASE=mysterylunch APP_ENV=local

before_script:
  - composer install --dev --prefer-source --no-interaction
  - mysql -e 'create database mysterylunch;'
  - php artisan migrate
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v