language: php

php:
  - 5.5
  - 5.6

env:
  - DB_USERNAME=root DB_DATABASE=mysterylunch APP_ENV=local

before_script:
  - composer install --dev --prefer-source --no-interaction
  - mysql -e 'create database mysterylunch;'
  - php artisan migrate
script: vendor/bin/phpunit